<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="MAM2021 || Data enthusiast">
	<meta name="author" content="Derek Leung">
	<meta name="generator" content="Hugo 0.74.3" />
	<title>Case Study -- The Lending Club &middot; Derek Leung&#39;s Portfolio</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Derek Leung</strong> <span>IP</span></a>
        <nav>
            <a href="#menu"></a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/blogs">Blogs</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">My Projects</a></li>
            
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Case Study -- The Lending Club</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/blogs/pic10.jpg" alt="" /></span>
                            
                            


<div id="load-and-prepare-the-data" class="section level1">
<h1>Load and prepare the data</h1>
<p>We start by loading the data to R in a dataframe.</p>
<pre class="r"><code>lc_raw &lt;- read_csv(&quot;/Users/dl/Documents/MAM/individual_portfolio/data/LendingClub Data.csv&quot;,  skip=1) %&gt;%  clean_names() # use janitor::clean_names()</code></pre>
</div>
<div id="ice-the-data-inspect-clean-explore" class="section level1">
<h1>ICE the data: Inspect, Clean, Explore</h1>
<p>Any data science engagement starts with ICE. Inspect, Clean and Explore the data.</p>
<pre class="r"><code>glimpse(lc_raw) </code></pre>
<pre><code>## Rows: 42,538
## Columns: 80
## $ int_rate            &lt;dbl&gt; 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0…
## $ loan_amnt           &lt;dbl&gt; 8000, 6000, 6500, 8000, 5500, 6000, 10200, 15000,…
## $ term_months         &lt;dbl&gt; 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 3…
## $ installment         &lt;dbl&gt; 241.28, 180.96, 196.04, 241.28, 165.88, 180.96, 3…
## $ dti                 &lt;dbl&gt; 2.11, 5.73, 17.68, 22.71, 5.75, 21.92, 18.62, 9.7…
## $ delinq_2yrs         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ annual_inc          &lt;dbl&gt; 50000, 52800, 35352, 79200, 240000, 89000, 110000…
## $ grade               &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;,…
## $ emp_title           &lt;chr&gt; NA, &quot;coral graphics&quot;, NA, &quot;Honeywell&quot;, &quot;O T Plus,…
## $ emp_length          &lt;chr&gt; &quot;5 years&quot;, &quot;&lt; 1 year&quot;, &quot;n/a&quot;, &quot;n/a&quot;, &quot;10+ years&quot;,…
## $ home_ownership      &lt;chr&gt; &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;…
## $ verification_status &lt;chr&gt; &quot;Verified&quot;, &quot;Source Verified&quot;, &quot;Not Verified&quot;, &quot;V…
## $ issue_d             &lt;chr&gt; &quot;9/1/2011&quot;, &quot;9/1/2011&quot;, &quot;9/1/2011&quot;, &quot;9/1/2011&quot;, &quot;…
## $ zip_code            &lt;chr&gt; &quot;977xx&quot;, &quot;228xx&quot;, &quot;864xx&quot;, &quot;322xx&quot;, &quot;278xx&quot;, &quot;760…
## $ addr_state          &lt;chr&gt; &quot;OR&quot;, &quot;VA&quot;, &quot;AZ&quot;, &quot;FL&quot;, &quot;NC&quot;, &quot;TX&quot;, &quot;CT&quot;, &quot;WA&quot;, &quot;…
## $ loan_status         &lt;chr&gt; &quot;Fully Paid&quot;, &quot;Charged Off&quot;, &quot;Fully Paid&quot;, &quot;Fully…
## $ desc                &lt;chr&gt; &quot;Borrower added on 09/08/11 &gt; Consolidating debt …
## $ purpose             &lt;chr&gt; &quot;debt_consolidation&quot;, &quot;vacation&quot;, &quot;credit_card&quot;, …
## $ title               &lt;chr&gt; &quot;Credit Card Payoff $8K&quot;, &quot;bad choice&quot;, &quot;Credit C…
## $ x20                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x21                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x22                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x23                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x24                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x25                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x26                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x27                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x28                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x29                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x30                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x31                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x32                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x33                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x34                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x35                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x36                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x37                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x38                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x39                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x40                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x41                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x42                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x43                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x44                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x45                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x46                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x47                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x48                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x49                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x50                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x51                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x52                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x53                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x54                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x55                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x56                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x57                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x58                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x59                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x60                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x61                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x62                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x63                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x64                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x65                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x66                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x67                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x68                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x69                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x70                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x71                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x72                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x73                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x74                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x75                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x76                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x77                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x78                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x79                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ x80                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
<pre class="r"><code>lc_clean&lt;- lc_raw %&gt;%
  dplyr::select(-x20:-x80) %&gt;% #delete empty columns
  filter(!is.na(int_rate)) %&gt;%   #delete empty rows
  mutate(
    issue_d = mdy(issue_d),  # lubridate::mdy() to fix date format
    term = factor(term_months),     # turn &#39;term&#39; into a categorical variable
    delinq_2yrs = factor(delinq_2yrs) # turn &#39;delinq_2yrs&#39; into a categorical variable
  ) %&gt;% 
  dplyr::select(-emp_title,-installment, -term_months, everything()) %&gt;% mutate(emp_length=as.factor(emp_length)) #move some not-so-important variables to the end. 


glimpse(lc_clean) </code></pre>
<pre><code>## Rows: 37,869
## Columns: 20
## $ int_rate            &lt;dbl&gt; 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0…
## $ loan_amnt           &lt;dbl&gt; 8000, 6000, 6500, 8000, 5500, 6000, 10200, 15000,…
## $ dti                 &lt;dbl&gt; 2.11, 5.73, 17.68, 22.71, 5.75, 21.92, 18.62, 9.7…
## $ delinq_2yrs         &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ annual_inc          &lt;dbl&gt; 50000, 52800, 35352, 79200, 240000, 89000, 110000…
## $ grade               &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;,…
## $ emp_length          &lt;fct&gt; 5 years, &lt; 1 year, n/a, n/a, 10+ years, 2 years, …
## $ home_ownership      &lt;chr&gt; &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;…
## $ verification_status &lt;chr&gt; &quot;Verified&quot;, &quot;Source Verified&quot;, &quot;Not Verified&quot;, &quot;V…
## $ issue_d             &lt;date&gt; 2011-09-01, 2011-09-01, 2011-09-01, 2011-09-01, …
## $ zip_code            &lt;chr&gt; &quot;977xx&quot;, &quot;228xx&quot;, &quot;864xx&quot;, &quot;322xx&quot;, &quot;278xx&quot;, &quot;760…
## $ addr_state          &lt;chr&gt; &quot;OR&quot;, &quot;VA&quot;, &quot;AZ&quot;, &quot;FL&quot;, &quot;NC&quot;, &quot;TX&quot;, &quot;CT&quot;, &quot;WA&quot;, &quot;…
## $ loan_status         &lt;chr&gt; &quot;Fully Paid&quot;, &quot;Charged Off&quot;, &quot;Fully Paid&quot;, &quot;Fully…
## $ desc                &lt;chr&gt; &quot;Borrower added on 09/08/11 &gt; Consolidating debt …
## $ purpose             &lt;chr&gt; &quot;debt_consolidation&quot;, &quot;vacation&quot;, &quot;credit_card&quot;, …
## $ title               &lt;chr&gt; &quot;Credit Card Payoff $8K&quot;, &quot;bad choice&quot;, &quot;Credit C…
## $ term                &lt;fct&gt; 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 3…
## $ term_months         &lt;dbl&gt; 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 3…
## $ installment         &lt;dbl&gt; 241.28, 180.96, 196.04, 241.28, 165.88, 180.96, 3…
## $ emp_title           &lt;chr&gt; NA, &quot;coral graphics&quot;, NA, &quot;Honeywell&quot;, &quot;O T Plus,…</code></pre>
<pre class="r"><code>summary(lc_clean)</code></pre>
<pre><code>##     int_rate        loan_amnt          dti         delinq_2yrs   
##  Min.   :0.0500   Min.   :  500   Min.   : 0.00   0      :33782  
##  1st Qu.:0.0900   1st Qu.: 5500   1st Qu.: 8.14   1      : 3141  
##  Median :0.1200   Median :10000   Median :13.36   2      :  637  
##  Mean   :0.1203   Mean   :11253   Mean   :13.28   3      :  213  
##  3rd Qu.:0.1500   3rd Qu.:15000   3rd Qu.:18.58   4      :   56  
##  Max.   :0.2500   Max.   :35000   Max.   :29.99   5      :   22  
##                                                   (Other):   18  
##    annual_inc         grade               emp_length    home_ownership    
##  Min.   :   4000   Length:37869       10+ years: 8405   Length:37869      
##  1st Qu.:  40800   Class :character   &lt; 1 year : 4384   Class :character  
##  Median :  59534   Mode  :character   2 years  : 4168   Mode  :character  
##  Mean   :  69148                      3 years  : 3910                     
##  3rd Qu.:  82800                      4 years  : 3305                     
##  Max.   :6000000                      5 years  : 3146                     
##                                       (Other)  :10551                     
##  verification_status    issue_d             zip_code          addr_state       
##  Length:37869        Min.   :2007-06-01   Length:37869       Length:37869      
##  Class :character    1st Qu.:2010-05-01   Class :character   Class :character  
##  Mode  :character    Median :2011-02-01   Mode  :character   Mode  :character  
##                      Mean   :2010-11-05                                        
##                      3rd Qu.:2011-08-01                                        
##                      Max.   :2011-12-01                                        
##                                                                                
##  loan_status            desc             purpose             title          
##  Length:37869       Length:37869       Length:37869       Length:37869      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##  term        term_months     installment       emp_title        
##  36:27674   Min.   :36.00   Min.   :  15.68   Length:37869      
##  60:10195   1st Qu.:36.00   1st Qu.: 168.59   Class :character  
##             Median :36.00   Median : 288.33   Mode  :character  
##             Mean   :42.46   Mean   : 332.58                     
##             3rd Qu.:60.00   3rd Qu.: 449.05                     
##             Max.   :60.00   Max.   :1305.19                     
## </code></pre>
<p>The data is now in a clean format stored in the dataframe “lc_clean.”</p>
</div>
<div id="q1.-explore-the-data-by-building-some-visualizations-as-suggested-below." class="section level1">
<h1>Q1. Explore the data by building some visualizations as suggested below.</h1>
<pre class="r"><code># Build a histogram of interest rates. Make sure it looks nice!
ggplot(lc_clean, aes(x=int_rate))+ 
  geom_histogram(bins=20) + 
  labs(title=&quot;Histogram of Interest Rate&quot;,
       x=&quot;Interest Rate&quot;,
       y=&quot;Count&quot;)+
  scale_x_continuous(labels = scales::percent)+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-1.png" width="672" /></p>
<pre class="r"><code># Build a histogram of interest rates but use different color for loans of different grades 
ggplot(lc_clean, aes(x=int_rate, fill=grade))+ 
  geom_histogram(bins=20)+
  labs(title=&quot;Histogram of Interest Rate by Grade&quot;,
       x=&quot;Interest Rate&quot;,
       y=&quot;Count&quot;)+
  scale_x_continuous(labels = scales::percent)+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-2.png" width="672" /></p>
<pre class="r"><code># Produce a scatter plot of loan amount against interest rate and add visually the line of best fit
ggplot(lc_clean[seq(1, nrow(lc_clean), 10), ] , aes(y=int_rate, x=loan_amnt)) +  geom_smooth(method=&quot;lm&quot;,se=0)+
  geom_point()+
scale_x_continuous(label=scales::dollar)+
  labs(y=&quot;Interest Rate&quot;, x=&quot;Annual Income&quot;)+
  theme_bw()</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-3.png" width="672" /></p>
<pre class="r"><code># Produce a scatter plot of annual income against interest rate and add visually the line of best fit 
ggplot(lc_clean[seq(1, nrow(lc_clean), 10), ] , aes(y=int_rate, x=annual_inc)) + 
  geom_point(size=0.1)+ 
  geom_smooth(method=&quot;lm&quot;, se=0) +
  scale_x_continuous(label=scales::dollar)+
  labs(y=&quot;Interest Rate&quot;, x=&quot;Annual Income&quot;)+
  theme_bw()</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-4.png" width="672" /></p>
<pre class="r"><code># In the same axes, produce box plots of the interest rate for every value of delinquencies
ggplot(lc_clean , aes(y=int_rate, x=delinq_2yrs, colour= delinq_2yrs)) + 
  geom_boxplot()+
  # geom_jitter()+
  theme_bw()+
   scale_y_continuous(labels=scales::percent)+
  theme(legend.position = &quot;none&quot;)+
  labs(
    title = &quot;Do delinquencies in the last two years impact interest rate charged?&quot;,
    x= &quot;Number of delinquecies in last two years&quot;, y=&quot;Interest Rate&quot;
  )+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-5.png" width="672" /></p>
<pre class="r"><code>#Create our own ones as well

#loan period vs interest rate
ggplot(lc_clean, aes(x=term, y = int_rate))+
  geom_boxplot()+
  labs(title=&quot;Interest Rate Spread by Loan Term&quot;,
       x=&quot;Loan Term in Months&quot;,
       y=&quot;Interest Rate&quot;)+
  scale_y_continuous(labels=scales::percent)+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-6.png" width="672" /></p>
<pre class="r"><code>#home ownership vs interest rate
ggplot(lc_clean, aes(x=home_ownership, y = int_rate))+
  geom_boxplot()+
  labs(title=&quot;Interest Rate Spread by Ownership Status&quot;,
       x=&quot;Ownership Status&quot;,
       y=&quot;Interest Rate&quot;)+
  scale_y_continuous(labels=scales::percent)+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-7.png" width="672" /></p>
<pre class="r"><code>#Employment Length vs Interest 
ggplot(lc_clean, aes(x=emp_length, y = int_rate))+
  geom_boxplot()+
  labs(title=&quot;Interest Rate Spread by Ownership Status&quot;,
       x=&quot;Ownership Status&quot;,
       y=&quot;Interest Rate&quot;)+
  scale_y_continuous(labels=scales::percent)+
  theme_bw()</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/data_visualisation-8.png" width="672" /></p>
</div>
<div id="estimate-simple-linear-regression-models" class="section level1">
<h1>Estimate simple linear regression models</h1>
<p>We start with a simple but quite powerful model.</p>
<pre class="r"><code>#Use the lm command to estimate a regression model with the following variables &quot;loan_amnt&quot;,  &quot;term&quot;, &quot;dti&quot;, &quot;annual_inc&quot;, and &quot;grade&quot;

model1&lt;-lm( int_rate ~ loan_amnt+ term+ dti+ annual_inc+ grade, data = lc_clean
  )
summary(model1) # noticed that annual income has a p value of over 0.05</code></pre>
<pre><code>## 
## Call:
## lm(formula = int_rate ~ loan_amnt + term + dti + annual_inc + 
##     grade, data = lc_clean)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.118827 -0.007035 -0.000342  0.006828  0.035081 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  7.169e-02  1.689e-04 424.363  &lt; 2e-16 ***
## loan_amnt    1.475e-07  8.284e-09  17.809  &lt; 2e-16 ***
## term60       3.608e-03  1.419e-04  25.431  &lt; 2e-16 ***
## dti          4.328e-05  8.269e-06   5.234 1.66e-07 ***
## annual_inc  -9.734e-10  9.283e-10  -1.049    0.294    
## gradeB       3.554e-02  1.492e-04 238.248  &lt; 2e-16 ***
## gradeC       6.016e-02  1.658e-04 362.783  &lt; 2e-16 ***
## gradeD       8.172e-02  1.906e-04 428.746  &lt; 2e-16 ***
## gradeE       9.999e-02  2.483e-04 402.660  &lt; 2e-16 ***
## gradeF       1.195e-01  3.673e-04 325.408  &lt; 2e-16 ***
## gradeG       1.355e-01  6.208e-04 218.245  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01056 on 37858 degrees of freedom
## Multiple R-squared:  0.9198, Adjusted R-squared:  0.9197 
## F-statistic: 4.34e+04 on 10 and 37858 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="q2.-answer-the-following-questions-on-model-1." class="section level2 unnumbered">
<h2>Q2. Answer the following questions on model 1.</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Are all variables statistically significant?
&gt;We noticed that in model1 annual_inc is the only insignificant variable. Therefore, it will be reasonable to exclude it in our future models.</p></li>
<li><p>How do you interpret the coefficient of the Term60 dummy variable? Of the grade B dummy variable?
&gt;All things being equal and on average compared to term 30, the interest rate increases by 3.608e-03 percentage point if the lending time amounts to 60 (term is equal to 60).
&gt;All things being equal and on average compared to grade A, the interest rate increases by 3.554e-02 percentage point if the grade of user is B category.</p></li>
<li><p>How much explanatory power does the model have?
&gt;Our model has 91.97% explanatory power (we checked it looking at Adjusted R-squared).</p></li>
<li><p>Approximately, how wide would the 95% confidence interval of any prediction based on this model be?
&gt;Our 95% Confidence Interval of any prediction based on model1, would amount to 1.96*0.01056 = ~±0.021.</p></li>
</ol>
</div>
</div>
<div id="feature-engineering" class="section level1">
<h1>Feature Engineering</h1>
<p>Let’s build progressively more complex models with more features.</p>
<pre class="r"><code>#Add to the previous model an interaction between loan amount and grade. Use the &quot;var1*var2&quot; notation to define an interaction term in the linear regression model. This will add the interaction and the individual variables to the model. 
model2 &lt;-lm( int_rate ~ loan_amnt*grade+ term+ dti+ annual_inc, data = lc_clean
  )

summary(model2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = int_rate ~ loan_amnt * grade + term + dti + annual_inc, 
##     data = lc_clean)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119807 -0.007230 -0.000057  0.006588  0.037460 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       7.171e-02  2.345e-04 305.762  &lt; 2e-16 ***
## loan_amnt         1.528e-07  2.028e-08   7.537 4.91e-14 ***
## gradeB            3.623e-02  2.732e-04 132.619  &lt; 2e-16 ***
## gradeC            6.198e-02  2.988e-04 207.452  &lt; 2e-16 ***
## gradeD            8.082e-02  3.483e-04 232.034  &lt; 2e-16 ***
## gradeE            9.633e-02  4.625e-04 208.293  &lt; 2e-16 ***
## gradeF            1.143e-01  7.735e-04 147.699  &lt; 2e-16 ***
## gradeG            1.327e-01  1.551e-03  85.580  &lt; 2e-16 ***
## term60            3.793e-03  1.424e-04  26.636  &lt; 2e-16 ***
## dti               3.836e-05  8.250e-06   4.649 3.34e-06 ***
## annual_inc       -1.224e-09  9.249e-10  -1.324  0.18564    
## loan_amnt:gradeB -6.617e-08  2.441e-08  -2.710  0.00673 ** 
## loan_amnt:gradeC -1.704e-07  2.621e-08  -6.500 8.14e-11 ***
## loan_amnt:gradeD  6.703e-08  2.798e-08   2.395  0.01662 *  
## loan_amnt:gradeE  2.209e-07  3.016e-08   7.323 2.47e-13 ***
## loan_amnt:gradeF  2.779e-07  4.136e-08   6.720 1.85e-11 ***
## loan_amnt:gradeG  1.265e-07  7.260e-08   1.743  0.08140 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01052 on 37852 degrees of freedom
## Multiple R-squared:  0.9204, Adjusted R-squared:  0.9204 
## F-statistic: 2.735e+04 on 16 and 37852 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Add to the model the square and the cube of annual income. Use the poly(var_name,3) command as a variable in the linear regression model.  
model3 &lt;- lm( int_rate ~ loan_amnt*grade+ term+ dti+poly(annual_inc,3), data = lc_clean
  ) 
summary(model3) # makes no difference</code></pre>
<pre><code>## 
## Call:
## lm(formula = int_rate ~ loan_amnt * grade + term + dti + poly(annual_inc, 
##     3), data = lc_clean)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119814 -0.007238 -0.000065  0.006594  0.037471 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           7.161e-02  2.279e-04 314.200  &lt; 2e-16 ***
## loan_amnt             1.556e-07  2.047e-08   7.600 3.03e-14 ***
## gradeB                3.623e-02  2.732e-04 132.611  &lt; 2e-16 ***
## gradeC                6.198e-02  2.988e-04 207.398  &lt; 2e-16 ***
## gradeD                8.081e-02  3.483e-04 231.999  &lt; 2e-16 ***
## gradeE                9.633e-02  4.625e-04 208.283  &lt; 2e-16 ***
## gradeF                1.143e-01  7.736e-04 147.695  &lt; 2e-16 ***
## gradeG                1.327e-01  1.551e-03  85.573  &lt; 2e-16 ***
## term60                3.786e-03  1.426e-04  26.546  &lt; 2e-16 ***
## dti                   3.761e-05  8.294e-06   4.535 5.79e-06 ***
## poly(annual_inc, 3)1 -1.589e-02  1.117e-02  -1.423   0.1549    
## poly(annual_inc, 3)2  6.296e-03  1.086e-02   0.580   0.5621    
## poly(annual_inc, 3)3 -8.981e-03  1.084e-02  -0.828   0.4076    
## loan_amnt:gradeB     -6.633e-08  2.442e-08  -2.717   0.0066 ** 
## loan_amnt:gradeC     -1.703e-07  2.621e-08  -6.498 8.23e-11 ***
## loan_amnt:gradeD      6.709e-08  2.798e-08   2.398   0.0165 *  
## loan_amnt:gradeE      2.209e-07  3.016e-08   7.324 2.45e-13 ***
## loan_amnt:gradeF      2.780e-07  4.136e-08   6.722 1.82e-11 ***
## loan_amnt:gradeG      1.270e-07  7.260e-08   1.750   0.0801 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01052 on 37850 degrees of freedom
## Multiple R-squared:  0.9204, Adjusted R-squared:  0.9204 
## F-statistic: 2.431e+04 on 18 and 37850 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Continuing with the previous model, instead of annual income as a continuous variable break it down into quartiles and use quartile dummy variables. You can do this with the following command. 
  
lc_clean2 &lt;- lc_clean %&gt;% 
  mutate(quartiles_annual_inc = as.factor(ntile(annual_inc, 4)))

model4 &lt;-lm( int_rate ~ loan_amnt*grade+ term+ dti+quartiles_annual_inc, data = lc_clean2
  ) 
summary(model4)  # still makes no difference</code></pre>
<pre><code>## 
## Call:
## lm(formula = int_rate ~ loan_amnt * grade + term + dti + quartiles_annual_inc, 
##     data = lc_clean2)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119767 -0.007203 -0.000064  0.006596  0.037581 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            7.187e-02  2.414e-04 297.700  &lt; 2e-16 ***
## loan_amnt              1.615e-07  2.048e-08   7.889 3.13e-15 ***
## gradeB                 3.622e-02  2.733e-04 132.524  &lt; 2e-16 ***
## gradeC                 6.196e-02  2.989e-04 207.272  &lt; 2e-16 ***
## gradeD                 8.079e-02  3.484e-04 231.877  &lt; 2e-16 ***
## gradeE                 9.632e-02  4.625e-04 208.273  &lt; 2e-16 ***
## gradeF                 1.143e-01  7.735e-04 147.723  &lt; 2e-16 ***
## gradeG                 1.327e-01  1.551e-03  85.570  &lt; 2e-16 ***
## term60                 3.781e-03  1.425e-04  26.532  &lt; 2e-16 ***
## dti                    3.672e-05  8.259e-06   4.446 8.78e-06 ***
## quartiles_annual_inc2 -2.619e-04  1.548e-04  -1.692  0.09068 .  
## quartiles_annual_inc3 -3.992e-04  1.590e-04  -2.510  0.01208 *  
## quartiles_annual_inc4 -5.382e-04  1.692e-04  -3.181  0.00147 ** 
## loan_amnt:gradeB      -6.638e-08  2.441e-08  -2.719  0.00655 ** 
## loan_amnt:gradeC      -1.699e-07  2.621e-08  -6.483 9.10e-11 ***
## loan_amnt:gradeD       6.770e-08  2.798e-08   2.419  0.01555 *  
## loan_amnt:gradeE       2.203e-07  3.016e-08   7.304 2.85e-13 ***
## loan_amnt:gradeF       2.766e-07  4.136e-08   6.687 2.30e-11 ***
## loan_amnt:gradeG       1.267e-07  7.259e-08   1.746  0.08089 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01052 on 37850 degrees of freedom
## Multiple R-squared:  0.9204, Adjusted R-squared:  0.9204 
## F-statistic: 2.432e+04 on 18 and 37850 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Compare the performance of these four models using the anova command
anova(model1, model2, model3, model4
      )</code></pre>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:Feature Engineering">
<col><col><col><col><col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Res.Df</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">RSS</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Df</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Sum of Sq</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">F</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Pr(&gt;F)</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">3.79e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">4.22</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.79e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">4.19</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.0332&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">50&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.64e-61</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">3.78e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">4.19</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">2</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.000107</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.484</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.616&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3.78e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">4.19</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.000915</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
</table>

<div id="q3.-answer-the-following-questions" class="section level2 unnumbered">
<h2>Q3. Answer the following questions</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Which of the four models has the most explanatory power in sample
&gt; Models 2, 3 &amp; 4 have the most explanatory power amounting to 0.9204. (The Adjusted R-squared is the same for all the 3 models)</p></li>
<li><p>In model 2, how do you interpret the estimated coefficient of the interaction term between grade B and loan amount?
&gt;All things being equal and on average compared to grade A, if the loan amount increase by 10 000, the interest rate for grade B useres will decrease by 6.617e-04 percentage point.</p></li>
<li><p>The problem of multicolinearity describes the situations where one feature is highly correlated with other fueatures (or with a linear combination of other features). If your goal is to use the model to make predictions, should you be concerned by the problem of multicolinearity? Why, or why not?
&gt; Multicolinearity impacts inference more than prediction, so for the case of prediction it is not very relevant. However, if one is using the model to explain their existing dataset they may have inaccurate results.</p></li>
</ol>
</div>
</div>
<div id="out-of-sample-testing" class="section level1">
<h1>Out of sample testing</h1>
<p>Let’s check the predictive accuracy of model2 by holding out a subset of the data to use as testing. This method is sometimes refered to as the hold-out method for out-of-sample testing.</p>
<pre class="r"><code>#split the data in dataframe called &quot;testing&quot; and another one called  &quot;training&quot;. The &quot;training&quot; dataframe should have 80% of the data and the &quot;testing&quot; dataframe 20%.
set.seed(176823769)
train_test_split &lt;- initial_split(lc_clean2, prop=0.8) # splitting dataset
lc_clean_train&lt;- training(train_test_split)
lc_clean_test&lt;- testing(train_test_split) 


#Fit model2 on the training set 
model2_training&lt;-lm(int_rate ~ loan_amnt + term+ dti + annual_inc + grade +grade:loan_amnt, data=lc_clean_train)
summary(model2_training)</code></pre>
<pre><code>## 
## Call:
## lm(formula = int_rate ~ loan_amnt + term + dti + annual_inc + 
##     grade + grade:loan_amnt, data = lc_clean_train)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119766 -0.007211 -0.000044  0.006588  0.037641 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       7.162e-02  2.637e-04 271.568  &lt; 2e-16 ***
## loan_amnt         1.586e-07  2.251e-08   7.045 1.89e-12 ***
## term60            3.772e-03  1.592e-04  23.691  &lt; 2e-16 ***
## dti               4.069e-05  9.232e-06   4.407 1.05e-05 ***
## annual_inc       -8.114e-10  1.195e-09  -0.679  0.49710    
## gradeB            3.622e-02  3.040e-04 119.160  &lt; 2e-16 ***
## gradeC            6.197e-02  3.329e-04 186.186  &lt; 2e-16 ***
## gradeD            8.088e-02  3.870e-04 209.006  &lt; 2e-16 ***
## gradeE            9.605e-02  5.146e-04 186.643  &lt; 2e-16 ***
## gradeF            1.140e-01  8.721e-04 130.704  &lt; 2e-16 ***
## gradeG            1.338e-01  1.747e-03  76.571  &lt; 2e-16 ***
## loan_amnt:gradeB -7.332e-08  2.717e-08  -2.699  0.00696 ** 
## loan_amnt:gradeC -1.755e-07  2.923e-08  -6.004 1.95e-09 ***
## loan_amnt:gradeD  6.792e-08  3.114e-08   2.181  0.02916 *  
## loan_amnt:gradeE  2.292e-07  3.346e-08   6.851 7.49e-12 ***
## loan_amnt:gradeF  2.973e-07  4.619e-08   6.436 1.24e-10 ***
## loan_amnt:gradeG  7.974e-08  8.208e-08   0.971  0.33132    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01049 on 30279 degrees of freedom
## Multiple R-squared:  0.9209, Adjusted R-squared:  0.9208 
## F-statistic: 2.203e+04 on 16 and 30279 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Calculate the RMSE of the model in the training set (in sample)
rmse_training&lt;-sqrt(mean((residuals(model2_training))^2))
#USe the model to make predictions out of sample in the testing set
pred&lt;-predict(model2_training,lc_clean_test)
#Calculate the RMSE of the model in the testing set (out of sample)
rmse_testing&lt;- RMSE(pred,lc_clean_test$int_rate)

rmse_training</code></pre>
<pre><code>## [1] 0.01048876</code></pre>
<pre class="r"><code>rmse_testing</code></pre>
<pre><code>## [1] 0.01061575</code></pre>
<div id="q4.-how-much-does-the-predictive-accuracy-of-model-2-deteriorate-when-we-move-from-in-sample-to-out-of-sample-testing-is-this-sensitive-to-the-random-seed-chosen-is-there-any-evidence-of-overfitting" class="section level2 unnumbered">
<h2>Q4. How much does the predictive accuracy of model 2 deteriorate when we move from in sample to out of sample testing? Is this sensitive to the random seed chosen? Is there any evidence of overfitting?</h2>
<blockquote>
<p>The predictive accuracy of model 2 does not much deteriorate when we move from in sample to out of sample testing. For purpose of checking it we compare the rmse_training to rmse_testing (0.0104 compared to 0.01061). We tried to check if the model is sensitive for the multiple random seed choices and we discovered that the model is not much sensitive (rmse is still a factor of e-2). There isn’t any evidence of overfitting.</p>
</blockquote>
</div>
</div>
<div id="k-fold-cross-validation" class="section level1">
<h1>k-fold cross validation</h1>
<p>We can also do out of sample testing using the method of k-fold cross validation. Using the caret package this is easy.</p>
<pre class="r"><code>#the method &quot;cv&quot; stands for cross validation. We re going to create 10 folds.  

control &lt;- trainControl (
    method=&quot;cv&quot;,
    number=10,
    verboseIter=TRUE) #by setting this to true the model will report its progress after each estimation

#we are going to train the model and report the results using k-fold cross validation
plsFit&lt;-train(
    int_rate ~ loan_amnt + term+ dti + annual_inc + grade +grade:loan_amnt ,
    lc_clean,
   method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE 
## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(plsFit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119807 -0.007230 -0.000057  0.006588  0.037460 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         7.171e-02  2.345e-04 305.762  &lt; 2e-16 ***
## loan_amnt           1.528e-07  2.028e-08   7.537 4.91e-14 ***
## term60              3.793e-03  1.424e-04  26.636  &lt; 2e-16 ***
## dti                 3.836e-05  8.250e-06   4.649 3.34e-06 ***
## annual_inc         -1.224e-09  9.249e-10  -1.324  0.18564    
## gradeB              3.623e-02  2.732e-04 132.619  &lt; 2e-16 ***
## gradeC              6.198e-02  2.988e-04 207.452  &lt; 2e-16 ***
## gradeD              8.082e-02  3.483e-04 232.034  &lt; 2e-16 ***
## gradeE              9.633e-02  4.625e-04 208.293  &lt; 2e-16 ***
## gradeF              1.143e-01  7.735e-04 147.699  &lt; 2e-16 ***
## gradeG              1.327e-01  1.551e-03  85.580  &lt; 2e-16 ***
## `loan_amnt:gradeB` -6.617e-08  2.441e-08  -2.710  0.00673 ** 
## `loan_amnt:gradeC` -1.704e-07  2.621e-08  -6.500 8.14e-11 ***
## `loan_amnt:gradeD`  6.703e-08  2.798e-08   2.395  0.01662 *  
## `loan_amnt:gradeE`  2.209e-07  3.016e-08   7.323 2.47e-13 ***
## `loan_amnt:gradeF`  2.779e-07  4.136e-08   6.720 1.85e-11 ***
## `loan_amnt:gradeG`  1.265e-07  7.260e-08   1.743  0.08140 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01052 on 37852 degrees of freedom
## Multiple R-squared:  0.9204, Adjusted R-squared:  0.9204 
## F-statistic: 2.735e+04 on 16 and 37852 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="q5.-compare-the-out-of-sample-rmse-of-10-fold-cross-validation-and-the-hold-out-method.-are-they-different-which-do-you-think-is-more-reliable-are-there-any-drawbacks-to-the-k-fold-cross-validation-method-compared-to-the-hold-out-method" class="section level2 unnumbered">
<h2>Q5. Compare the out-of-sample RMSE of 10-fold cross validation and the hold-out method. Are they different? Which do you think is more reliable? Are there any drawbacks to the k-fold cross validation method compared to the hold-out method?</h2>
<blockquote>
<p>Answer here: The RMSE for both moethds is the same, however the k-fold cross validation method gives a range of answers and is more reliable since it checks k times and for k samples. However, the drawback of k-fold cross validation is that it takes much longer time.</p>
</blockquote>
</div>
</div>
<div id="sample-size-estimation-and-learning-curves" class="section level1">
<h1>Sample size estimation and learning curves</h1>
<p>We can use the hold out method for out-of-sample testing to check if we have a sufficiently large sample to estimate the model reliably. The idea is to set aside some of the data as a testing set. From the remaining data draw progressively larger training sets and check how the performance of the model on the testing set changes. If the performance no longer improves with larger datasets we know we have a large enough sample. The code below does this. Examine it and run it with different random seeds.</p>
<pre class="r"><code>#select a testing dataset (25% of all data)
set.seed(12)

train_test_split &lt;- initial_split(lc_clean, prop = 0.75)
remaining &lt;- training(train_test_split)
testing &lt;- testing(train_test_split)

#We are now going to run 30 models starting from a tiny training set drawn from the training data and progressively increasing its size. The testing set remains the same in all iterations.

#initiating the model by setting some parameters to zero
rmse_sample &lt;- 0
sample_size&lt;-0
Rsq_sample&lt;-0

for(i in 1:30) {
#from the remaining dataset select a smaller subset to training the data
set.seed(100)
sample

  learning_split &lt;- initial_split(remaining, prop = i/200)
  training &lt;- training(learning_split)
  sample_size[i]=nrow(training)
  
  #traing the model on the small dataset
  model3&lt;-lm(int_rate ~ loan_amnt + term+ dti + annual_inc + grade + grade:loan_amnt, training)
  #test the performance of the model on the large testing dataset. This stays fixed for all iterations.
  pred&lt;-predict(model3,testing)
  rmse_sample[i]&lt;-RMSE(pred,testing$int_rate)
  Rsq_sample[i]&lt;-R2(pred,testing$int_rate)
}</code></pre>
<pre><code>## Warning in predict.lm(model3, testing): prediction from a rank-deficient fit may
## be misleading</code></pre>
<pre class="r"><code>plot(sample_size,rmse_sample)</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/learning%20curves-1.png" width="672" /></p>
<pre class="r"><code>plot(sample_size,Rsq_sample)</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/learning%20curves-2.png" width="672" /></p>
<div id="q6.-using-the-learning-curves-above-approximately-how-large-of-a-sample-size-would-we-need-to-estimate-model-3-reliably-once-we-reach-this-sample-size-if-we-want-to-reduce-the-prediction-error-further-what-options-do-we-have" class="section level2 unnumbered">
<h2>Q6. Using the learning curves above, approximately how large of a sample size would we need to estimate model 3 reliably? Once we reach this sample size, if we want to reduce the prediction error further what options do we have?</h2>
<blockquote>
<p>Answer here: After analysing the graphs above, we noticed that the sample size that would estimate model 3 reliably is 1500. Once we reach this sample size, we can still try to reduce the prediction error by regularization or using the k-fold cross validation method.</p>
</blockquote>
</div>
</div>
<div id="regularization-using-lasso-regression" class="section level1">
<h1>Regularization using LASSO regression</h1>
<p>If we are in the region of the learning curve where we do not have enough data, one option is to use a regularization method such as LASSO.</p>
<p>Let’s try to estimate large and complicated model (many interactions and polynomials) on a small training dataset using OLS regression and hold-out validation method.</p>
<pre class="r"><code>#split the data in testing and training. The training test is really small.
set.seed(1234)
train_test_split &lt;- initial_split(lc_clean, prop = 0.01)
training &lt;- training(train_test_split)
testing &lt;- testing(train_test_split)

model_lm&lt;-lm(int_rate ~ poly(loan_amnt,3) + term+ dti + annual_inc + grade +grade:poly(loan_amnt,3):term +poly(loan_amnt,3):term +grade:term, training)
predictions &lt;- predict(model_lm,testing)</code></pre>
<pre><code>## Warning in predict.lm(model_lm, testing): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre class="r"><code># Model prediction performance
data.frame(
  RMSE = RMSE(predictions, testing$int_rate),
  Rsquare = R2(predictions, testing$int_rate)
)</code></pre>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:OLS model overfitting">
<col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">RMSE</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Rsquare</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.0446</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.352</td></tr>
</table>

<p>Not surprisingly this model does not perform well – as we knew form the learning curves we constructed for a simpler model we need a lot more data to estimate this model reliably. Try running it again with different seeds. The model’s performance tends to be sensitive to the choice of the training set.</p>
<p>LASSO regression offers one solution – it extends the OLS regression by penalizing the model for setting any coefficient to a value that is different from zero. The penalty is proportional to a parameter $$ (pronounced lambda). This parameter cannot be estimated directly (and for this reason sometimes it is refered to as hyperparameter) and will be selected through k-fold cross validation in order to provide the best out-of-sample performance. As result of the LASSO precedure, only those features that are more strongly associated with the outcome will have non-zero coefficients and the estimated model will be less sensitive to the training set. Sometimes LASSO regression is refered to as regularization.</p>
<pre class="r"><code>#we will look for the optimal lambda in this sequence (we will try 1000 different lambdas)
lambda_seq &lt;- seq(0, 0.01, length = 1000)
#lasso regression using k-fold cross validation to select the best lambda

lasso &lt;- train(
 int_rate ~ poly(loan_amnt,3) + term+ dti + annual_inc + grade +grade:poly(loan_amnt,3):term +poly(loan_amnt,3):term +grade:term,
 data = training,
 method = &quot;glmnet&quot;,
  preProc = c(&quot;center&quot;, &quot;scale&quot;), #This option standardizes the data before running the LASSO regression
  trControl = control,
  tuneGrid = expand.grid(alpha = 1, lambda = lambda_seq) #alpha=1 specifies to run a LASSO regression. If alpha=0 the model would run ridge regression.
  )</code></pre>
<pre><code>## + Fold01: alpha=1, lambda=0.01 
## - Fold01: alpha=1, lambda=0.01 
## + Fold02: alpha=1, lambda=0.01 
## - Fold02: alpha=1, lambda=0.01 
## + Fold03: alpha=1, lambda=0.01 
## - Fold03: alpha=1, lambda=0.01 
## + Fold04: alpha=1, lambda=0.01 
## - Fold04: alpha=1, lambda=0.01 
## + Fold05: alpha=1, lambda=0.01 
## - Fold05: alpha=1, lambda=0.01 
## + Fold06: alpha=1, lambda=0.01 
## - Fold06: alpha=1, lambda=0.01 
## + Fold07: alpha=1, lambda=0.01 
## - Fold07: alpha=1, lambda=0.01 
## + Fold08: alpha=1, lambda=0.01 
## - Fold08: alpha=1, lambda=0.01 
## + Fold09: alpha=1, lambda=0.01 
## - Fold09: alpha=1, lambda=0.01 
## + Fold10: alpha=1, lambda=0.01 
## - Fold10: alpha=1, lambda=0.01 
## Aggregating results
## Selecting tuning parameters
## Fitting alpha = 1, lambda = 0.000581 on full training set</code></pre>
<pre class="r"><code># Model coefficients
coef(lasso$finalModel, lasso$bestTune$lambda)</code></pre>
<pre><code>## 58 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                               1
## (Intercept)                        1.185298e-01
## poly(loan_amnt, 3)1                .           
## poly(loan_amnt, 3)2                .           
## poly(loan_amnt, 3)3                .           
## term60                             7.098602e-04
## dti                                .           
## annual_inc                         .           
## gradeB                             1.415886e-02
## gradeC                             2.280581e-02
## gradeD                             2.431974e-02
## gradeE                             2.278486e-02
## gradeF                             1.692347e-02
## gradeG                             7.860209e-03
## poly(loan_amnt, 3)1:term60         1.784368e-03
## poly(loan_amnt, 3)2:term60         .           
## poly(loan_amnt, 3)3:term60         .           
## term60:gradeB                      .           
## term60:gradeC                      .           
## term60:gradeD                      1.221352e-04
## term60:gradeE                      3.431031e-03
## term60:gradeF                      1.857156e-04
## term60:gradeG                      3.261629e-04
## poly(loan_amnt, 3)1:term36:gradeB  .           
## poly(loan_amnt, 3)2:term36:gradeB  .           
## poly(loan_amnt, 3)3:term36:gradeB  .           
## poly(loan_amnt, 3)1:term60:gradeB  .           
## poly(loan_amnt, 3)2:term60:gradeB  .           
## poly(loan_amnt, 3)3:term60:gradeB  .           
## poly(loan_amnt, 3)1:term36:gradeC -9.385425e-05
## poly(loan_amnt, 3)2:term36:gradeC  .           
## poly(loan_amnt, 3)3:term36:gradeC  .           
## poly(loan_amnt, 3)1:term60:gradeC -3.097033e-04
## poly(loan_amnt, 3)2:term60:gradeC  .           
## poly(loan_amnt, 3)3:term60:gradeC  .           
## poly(loan_amnt, 3)1:term36:gradeD -2.006746e-04
## poly(loan_amnt, 3)2:term36:gradeD  .           
## poly(loan_amnt, 3)3:term36:gradeD  .           
## poly(loan_amnt, 3)1:term60:gradeD  .           
## poly(loan_amnt, 3)2:term60:gradeD  .           
## poly(loan_amnt, 3)3:term60:gradeD  .           
## poly(loan_amnt, 3)1:term36:gradeE  .           
## poly(loan_amnt, 3)2:term36:gradeE  1.563861e-04
## poly(loan_amnt, 3)3:term36:gradeE -2.895880e-04
## poly(loan_amnt, 3)1:term60:gradeE  1.996920e-04
## poly(loan_amnt, 3)2:term60:gradeE  .           
## poly(loan_amnt, 3)3:term60:gradeE  1.773125e-04
## poly(loan_amnt, 3)1:term36:gradeF  .           
## poly(loan_amnt, 3)2:term36:gradeF  .           
## poly(loan_amnt, 3)3:term36:gradeF  .           
## poly(loan_amnt, 3)1:term60:gradeF  7.979355e-05
## poly(loan_amnt, 3)2:term60:gradeF  .           
## poly(loan_amnt, 3)3:term60:gradeF  .           
## poly(loan_amnt, 3)1:term36:gradeG  .           
## poly(loan_amnt, 3)2:term36:gradeG  .           
## poly(loan_amnt, 3)3:term36:gradeG  .           
## poly(loan_amnt, 3)1:term60:gradeG  3.954958e-06
## poly(loan_amnt, 3)2:term60:gradeG  5.059345e-08
## poly(loan_amnt, 3)3:term60:gradeG  .</code></pre>
<pre class="r"><code>#Best lambda
lasso$bestTune$lambda</code></pre>
<pre><code>## [1] 0.0005805806</code></pre>
<pre class="r"><code># Count of how many coefficients are greater than zero and how many are equal to zero
sum(coef(lasso$finalModel, lasso$bestTune$lambda)!=0)</code></pre>
<pre><code>## [1] 23</code></pre>
<pre class="r"><code>sum(coef(lasso$finalModel, lasso$bestTune$lambda)==0)</code></pre>
<pre><code>## [1] 35</code></pre>
<pre class="r"><code># Make predictions
predictions &lt;- predict(lasso,testing)

# Model prediction performance
data.frame(
  RMSE = RMSE(predictions, testing$int_rate),
  Rsquare = R2(predictions, testing$int_rate)
)</code></pre>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:LASSO compared to OLS">
<col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">RMSE</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Rsquare</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.0109</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.917</td></tr>
</table>

<div id="q7.-answer-the-following-questions" class="section level2 unnumbered">
<h2>Q7. Answer the following questions</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Which model performs best out of sample, OLS regression or LASSO?
&gt; From the above, we can infere that the LASSO regression method is a better fit with a much smaller RMSE and significantly larger Adjusted R-squared using only 0.01 of data.</p></li>
<li><p>What value of lambda offers best performance? Is this sensitive to the random seed?
&gt;The best performance lambda in the seed 1234 is equal to 0.0005805806. The lambda is very sensitive to random seed, however the output of LASSO regression seems consistent.</p></li>
<li><p>How many coefficients are zero and how many are non-zero in the LASSO model of best fit?
&gt; In our LASSO regression, 23 variables are equal to zero and 35 variables are not equal to 0.</p></li>
<li><p>Why is it important to standardize continuous variables before running LASSO?
&gt; Note in linear regression formula, the larger the values of the data, the smaller the coefficients. Since LASSO easily penalises small coefficients to zero, it is important to control the magnitude of data values before running regression.</p></li>
</ol>
</div>
</div>
<div id="using-time-information" class="section level1">
<h1>Using Time Information</h1>
<p>Let’s try to further improve the model’s predictive performance. So far we have not used any time series information. Effectively, all things being equal, our prediction for the interest rate of a loan given in 2009 would be the same as that of a loan given in 2011. Is this a good assumption?</p>
<p>First, investigate graphically whether there are any time trends in the interest rates. (Note that the variable “issue_d” only has information on the month the loan was awarded but not the exact date.) Can you use this information to further improve the forecasting accuracy of your model? Try controlling for time in a linear fashion (i.e., a linear time trend) and controlling for time as quarter dummies (this is a method to capture non-linear effects of time – we assume that the impact of time doesn’t change within a quarter but it can chance from quarter to quarter). Finally, check if time affect loans of different grades differently.</p>
<pre class="r"><code>#linear time trend (add code below)

ggplot(lc_clean, aes(x=issue_d,y=int_rate))+
  geom_point()+
  geom_smooth(method=&quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/time%20trends-1.png" width="672" /></p>
<pre class="r"><code>#linear time trend by grade (add code below)
ggplot(lc_clean, aes(x=issue_d,y=int_rate, colour=grade))+
  geom_point()+
  geom_smooth(method=&quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/time%20trends-2.png" width="672" /></p>
<pre class="r"><code>glimpse(lc_clean2)</code></pre>
<pre><code>## Rows: 37,869
## Columns: 21
## $ int_rate             &lt;dbl&gt; 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, …
## $ loan_amnt            &lt;dbl&gt; 8000, 6000, 6500, 8000, 5500, 6000, 10200, 15000…
## $ dti                  &lt;dbl&gt; 2.11, 5.73, 17.68, 22.71, 5.75, 21.92, 18.62, 9.…
## $ delinq_2yrs          &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ annual_inc           &lt;dbl&gt; 50000, 52800, 35352, 79200, 240000, 89000, 11000…
## $ grade                &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;…
## $ emp_length           &lt;fct&gt; 5 years, &lt; 1 year, n/a, n/a, 10+ years, 2 years,…
## $ home_ownership       &lt;chr&gt; &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, &quot;MORTGAGE&quot;, …
## $ verification_status  &lt;chr&gt; &quot;Verified&quot;, &quot;Source Verified&quot;, &quot;Not Verified&quot;, &quot;…
## $ issue_d              &lt;date&gt; 2011-09-01, 2011-09-01, 2011-09-01, 2011-09-01,…
## $ zip_code             &lt;chr&gt; &quot;977xx&quot;, &quot;228xx&quot;, &quot;864xx&quot;, &quot;322xx&quot;, &quot;278xx&quot;, &quot;76…
## $ addr_state           &lt;chr&gt; &quot;OR&quot;, &quot;VA&quot;, &quot;AZ&quot;, &quot;FL&quot;, &quot;NC&quot;, &quot;TX&quot;, &quot;CT&quot;, &quot;WA&quot;, …
## $ loan_status          &lt;chr&gt; &quot;Fully Paid&quot;, &quot;Charged Off&quot;, &quot;Fully Paid&quot;, &quot;Full…
## $ desc                 &lt;chr&gt; &quot;Borrower added on 09/08/11 &gt; Consolidating debt…
## $ purpose              &lt;chr&gt; &quot;debt_consolidation&quot;, &quot;vacation&quot;, &quot;credit_card&quot;,…
## $ title                &lt;chr&gt; &quot;Credit Card Payoff $8K&quot;, &quot;bad choice&quot;, &quot;Credit …
## $ term                 &lt;fct&gt; 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, …
## $ term_months          &lt;dbl&gt; 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, …
## $ installment          &lt;dbl&gt; 241.28, 180.96, 196.04, 241.28, 165.88, 180.96, …
## $ emp_title            &lt;chr&gt; NA, &quot;coral graphics&quot;, NA, &quot;Honeywell&quot;, &quot;O T Plus…
## $ quartiles_annual_inc &lt;fct&gt; 2, 2, 1, 3, 4, 4, 4, 4, 2, 2, 4, 3, 3, 2, 1, 3, …</code></pre>
<pre class="r"><code>#Train models using OLS regression and k-fold cross-validation
#The first model has some explanatory variables and a linear time trend

time1&lt;-train(
  int_rate ~ loan_amnt*grade+ term+ dti + issue_d,#fill your variables here &quot;+ issue_d&quot;
  lc_clean,
  method = &quot;lm&quot;,
  trControl = control)</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE 
## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(time1) # seems like dti is corrolated with issue_d (maybe lots of people defaulted because of the crisis)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.119019 -0.006587 -0.000749  0.006951  0.036179 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        -2.511e-02  2.512e-03 -10.000  &lt; 2e-16 ***
## loan_amnt           8.842e-08  1.984e-08   4.456 8.36e-06 ***
## gradeB              3.609e-02  2.680e-04 134.681  &lt; 2e-16 ***
## gradeC              6.247e-02  2.933e-04 212.962  &lt; 2e-16 ***
## gradeD              8.131e-02  3.418e-04 237.889  &lt; 2e-16 ***
## gradeE              9.729e-02  4.542e-04 214.172  &lt; 2e-16 ***
## gradeF              1.152e-01  7.591e-04 151.809  &lt; 2e-16 ***
## gradeG              1.337e-01  1.521e-03  87.877  &lt; 2e-16 ***
## term60              2.263e-03  1.451e-04  15.602  &lt; 2e-16 ***
## dti                 1.204e-05  8.037e-06   1.499   0.1340    
## issue_d             6.539e-06  1.691e-07  38.675  &lt; 2e-16 ***
## `loan_amnt:gradeB` -1.286e-11  2.401e-08  -0.001   0.9996    
## `loan_amnt:gradeC` -1.207e-07  2.574e-08  -4.689 2.76e-06 ***
## `loan_amnt:gradeD`  1.138e-07  2.747e-08   4.143 3.43e-05 ***
## `loan_amnt:gradeE`  2.459e-07  2.959e-08   8.311  &lt; 2e-16 ***
## `loan_amnt:gradeF`  3.012e-07  4.057e-08   7.424 1.16e-13 ***
## `loan_amnt:gradeG`  1.580e-07  7.120e-08   2.220   0.0265 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01031 on 37852 degrees of freedom
## Multiple R-squared:  0.9234, Adjusted R-squared:  0.9234 
## F-statistic: 2.853e+04 on 16 and 37852 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#The second model has a different linear time trend for each grade class
time2&lt;-train(
    int_rate ~ loan_amnt*grade+ term+ dti + issue_d*grade, #fill your variables here 
    lc_clean,
   method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE 
## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(time2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.120428 -0.006609 -0.000147  0.006760  0.030757 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         2.859e-01  4.356e-03  65.621  &lt; 2e-16 ***
## loan_amnt           3.033e-07  1.759e-08  17.239  &lt; 2e-16 ***
## gradeB             -2.297e-01  5.808e-03 -39.552  &lt; 2e-16 ***
## gradeC             -3.539e-01  6.179e-03 -57.274  &lt; 2e-16 ***
## gradeD             -5.145e-01  7.198e-03 -71.474  &lt; 2e-16 ***
## gradeE             -6.134e-01  9.905e-03 -61.926  &lt; 2e-16 ***
## gradeF             -7.105e-01  1.612e-02 -44.082  &lt; 2e-16 ***
## gradeG             -7.104e-01  3.314e-02 -21.434  &lt; 2e-16 ***
## term60             -6.086e-04  1.301e-04  -4.676 2.94e-06 ***
## dti                 5.759e-05  7.064e-06   8.152 3.69e-16 ***
## issue_d            -1.443e-05  2.935e-07 -49.168  &lt; 2e-16 ***
## `loan_amnt:gradeB` -1.558e-07  2.123e-08  -7.342 2.15e-13 ***
## `loan_amnt:gradeC` -3.237e-07  2.283e-08 -14.178  &lt; 2e-16 ***
## `loan_amnt:gradeD` -1.783e-07  2.435e-08  -7.322 2.48e-13 ***
## `loan_amnt:gradeE` -1.725e-07  2.659e-08  -6.488 8.82e-11 ***
## `loan_amnt:gradeF` -1.862e-07  3.677e-08  -5.064 4.13e-07 ***
## `loan_amnt:gradeG` -2.963e-07  6.439e-08  -4.602 4.21e-06 ***
## `gradeB:issue_d`    1.790e-05  3.903e-07  45.860  &lt; 2e-16 ***
## `gradeC:issue_d`    2.806e-05  4.165e-07  67.364  &lt; 2e-16 ***
## `gradeD:issue_d`    4.018e-05  4.850e-07  82.852  &lt; 2e-16 ***
## `gradeE:issue_d`    4.799e-05  6.680e-07  71.843  &lt; 2e-16 ***
## `gradeF:issue_d`    5.573e-05  1.085e-06  51.348  &lt; 2e-16 ***
## `gradeG:issue_d`    5.696e-05  2.230e-06  25.544  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.009049 on 37846 degrees of freedom
## Multiple R-squared:  0.9411, Adjusted R-squared:  0.941 
## F-statistic: 2.747e+04 on 22 and 37846 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Change the time trend to a quarter dummy variables.
#zoo::as.yearqrt() creates quarter dummies 
lc_clean_quarter&lt;-lc_clean %&gt;%
  mutate(yq = as.factor(as.yearqtr(lc_clean$issue_d, format = &quot;%Y-%m-%d&quot;)))



time3&lt;-train(
    int_rate ~loan_amnt*grade+ term+ dti + yq ,#fill your variables here 
    lc_clean_quarter,
     method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(time3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.115934 -0.005413 -0.000246  0.005794  0.037599 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         3.827e-02  9.076e-03   4.217 2.48e-05 ***
## loan_amnt           1.043e-07  1.750e-08   5.960 2.54e-09 ***
## gradeB              3.659e-02  2.358e-04 155.130  &lt; 2e-16 ***
## gradeC              6.250e-02  2.583e-04 241.955  &lt; 2e-16 ***
## gradeD              8.098e-02  3.009e-04 269.098  &lt; 2e-16 ***
## gradeE              9.700e-02  3.999e-04 242.537  &lt; 2e-16 ***
## gradeF              1.154e-01  6.678e-04 172.737  &lt; 2e-16 ***
## gradeG              1.338e-01  1.338e-03 100.000  &lt; 2e-16 ***
## term60              4.581e-03  1.308e-04  35.027  &lt; 2e-16 ***
## dti                 5.894e-06  7.072e-06   0.833 0.404594    
## `yq2007 Q3`         1.911e-02  9.135e-03   2.092 0.036420 *  
## `yq2007 Q4`         1.469e-02  9.103e-03   1.614 0.106478    
## `yq2008 Q1`         2.114e-02  9.082e-03   2.328 0.019928 *  
## `yq2008 Q2`         2.275e-02  9.090e-03   2.503 0.012318 *  
## `yq2008 Q3`         2.391e-02  9.100e-03   2.627 0.008608 ** 
## `yq2008 Q4`         3.183e-02  9.083e-03   3.504 0.000458 ***
## `yq2009 Q1`         3.601e-02  9.079e-03   3.967 7.30e-05 ***
## `yq2009 Q2`         3.786e-02  9.078e-03   4.171 3.04e-05 ***
## `yq2009 Q3`         3.939e-02  9.077e-03   4.340 1.43e-05 ***
## `yq2009 Q4`         3.965e-02  9.076e-03   4.369 1.25e-05 ***
## `yq2010 Q1`         3.463e-02  9.076e-03   3.815 0.000136 ***
## `yq2010 Q2`         3.338e-02  9.075e-03   3.678 0.000235 ***
## `yq2010 Q3`         3.447e-02  9.075e-03   3.798 0.000146 ***
## `yq2010 Q4`         2.575e-02  9.075e-03   2.837 0.004552 ** 
## `yq2011 Q1`         2.788e-02  9.075e-03   3.072 0.002128 ** 
## `yq2011 Q2`         3.304e-02  9.074e-03   3.641 0.000271 ***
## `yq2011 Q3`         3.544e-02  9.074e-03   3.905 9.42e-05 ***
## `yq2011 Q4`         4.168e-02  9.074e-03   4.593 4.39e-06 ***
## `loan_amnt:gradeB` -1.079e-07  2.117e-08  -5.098 3.45e-07 ***
## `loan_amnt:gradeC` -2.145e-07  2.271e-08  -9.446  &lt; 2e-16 ***
## `loan_amnt:gradeD`  5.841e-08  2.422e-08   2.411 0.015896 *  
## `loan_amnt:gradeE`  1.817e-07  2.609e-08   6.963 3.39e-12 ***
## `loan_amnt:gradeF`  2.266e-07  3.573e-08   6.343 2.28e-10 ***
## `loan_amnt:gradeG`  1.125e-07  6.264e-08   1.795 0.072595 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.00907 on 37835 degrees of freedom
## Multiple R-squared:  0.9408, Adjusted R-squared:  0.9408 
## F-statistic: 1.822e+04 on 33 and 37835 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#We specify one quarter dummy variable for each grade. This is going to be a large model as there are 19 quarters x 7 grades = 133 quarter-grade dummies.
time4&lt;-train(
    int_rate ~loan_amnt*grade+ term+ dti + yq*grade ,#fill your variables here 
    lc_clean_quarter,
     method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(time4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.120434 -0.004928  0.000306  0.004674  0.034225 
## 
## Coefficients: (11 not defined because of singularities)
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         1.860e-02  7.579e-03   2.454 0.014117 *  
## loan_amnt           2.972e-07  1.487e-08  19.984  &lt; 2e-16 ***
## gradeB              4.307e-02  3.192e-04 134.933  &lt; 2e-16 ***
## gradeC              6.975e-02  3.622e-04 192.587  &lt; 2e-16 ***
## gradeD              9.703e-02  4.188e-04 231.672  &lt; 2e-16 ***
## gradeE              1.177e-01  5.380e-04 218.712  &lt; 2e-16 ***
## gradeF              1.390e-01  8.637e-04 160.909  &lt; 2e-16 ***
## gradeG              1.603e-01  1.800e-03  89.025  &lt; 2e-16 ***
## term60              1.729e-03  1.128e-04  15.322  &lt; 2e-16 ***
## dti                 4.830e-05  5.921e-06   8.157 3.53e-16 ***
## `yq2007 Q3`         5.476e-02  7.721e-03   7.092 1.35e-12 ***
## `yq2007 Q4`         5.579e-02  7.711e-03   7.235 4.74e-13 ***
## `yq2008 Q1`         5.946e-02  7.616e-03   7.807 6.01e-15 ***
## `yq2008 Q2`         6.088e-02  7.651e-03   7.957 1.81e-15 ***
## `yq2008 Q3`         6.026e-02  7.688e-03   7.839 4.65e-15 ***
## `yq2008 Q4`         6.663e-02  7.616e-03   8.749  &lt; 2e-16 ***
## `yq2009 Q1`         6.834e-02  7.598e-03   8.994  &lt; 2e-16 ***
## `yq2009 Q2`         6.780e-02  7.593e-03   8.930  &lt; 2e-16 ***
## `yq2009 Q3`         6.597e-02  7.589e-03   8.693  &lt; 2e-16 ***
## `yq2009 Q4`         6.397e-02  7.587e-03   8.432  &lt; 2e-16 ***
## `yq2010 Q1`         5.696e-02  7.586e-03   7.509 6.10e-14 ***
## `yq2010 Q2`         5.488e-02  7.584e-03   7.237 4.67e-13 ***
## `yq2010 Q3`         5.484e-02  7.583e-03   7.233 4.82e-13 ***
## `yq2010 Q4`         4.379e-02  7.581e-03   5.776 7.70e-09 ***
## `yq2011 Q1`         4.567e-02  7.580e-03   6.025 1.71e-09 ***
## `yq2011 Q2`         4.655e-02  7.580e-03   6.142 8.25e-10 ***
## `yq2011 Q3`         4.674e-02  7.579e-03   6.167 7.05e-10 ***
## `yq2011 Q4`         5.374e-02  7.575e-03   7.094 1.32e-12 ***
## `loan_amnt:gradeB` -2.454e-07  1.794e-08 -13.679  &lt; 2e-16 ***
## `loan_amnt:gradeC` -3.708e-07  1.928e-08 -19.238  &lt; 2e-16 ***
## `loan_amnt:gradeD` -2.123e-07  2.056e-08 -10.328  &lt; 2e-16 ***
## `loan_amnt:gradeE` -2.250e-07  2.255e-08  -9.975  &lt; 2e-16 ***
## `loan_amnt:gradeF` -2.491e-07  3.154e-08  -7.900 2.87e-15 ***
## `loan_amnt:gradeG` -3.430e-07  5.653e-08  -6.068 1.31e-09 ***
## `gradeB:yq2007 Q3` -2.307e-02  2.299e-03 -10.034  &lt; 2e-16 ***
## `gradeC:yq2007 Q3` -3.555e-02  2.423e-03 -14.670  &lt; 2e-16 ***
## `gradeD:yq2007 Q3` -5.148e-02  3.711e-03 -13.874  &lt; 2e-16 ***
## `gradeE:yq2007 Q3` -5.687e-02  5.566e-03 -10.218  &lt; 2e-16 ***
## `gradeF:yq2007 Q3` -6.133e-02  3.760e-03 -16.314  &lt; 2e-16 ***
## `gradeG:yq2007 Q3`         NA         NA      NA       NA    
## `gradeB:yq2007 Q4` -2.403e-02  1.948e-03 -12.336  &lt; 2e-16 ***
## `gradeC:yq2007 Q4` -3.565e-02  1.799e-03 -19.820  &lt; 2e-16 ***
## `gradeD:yq2007 Q4` -5.005e-02  2.070e-03 -24.184  &lt; 2e-16 ***
## `gradeE:yq2007 Q4` -5.085e-02  2.723e-03 -18.677  &lt; 2e-16 ***
## `gradeF:yq2007 Q4` -5.441e-02  7.720e-03  -7.048 1.85e-12 ***
## `gradeG:yq2007 Q4`         NA         NA      NA       NA    
## `gradeB:yq2008 Q1` -2.294e-02  9.838e-04 -23.315  &lt; 2e-16 ***
## `gradeC:yq2008 Q1` -3.340e-02  1.049e-03 -31.841  &lt; 2e-16 ***
## `gradeD:yq2008 Q1` -4.555e-02  1.178e-03 -38.682  &lt; 2e-16 ***
## `gradeE:yq2008 Q1` -5.330e-02  1.655e-03 -32.212  &lt; 2e-16 ***
## `gradeF:yq2008 Q1` -5.639e-02  2.844e-03 -19.826  &lt; 2e-16 ***
## `gradeG:yq2008 Q1` -6.322e-02  5.523e-03 -11.447  &lt; 2e-16 ***
## `gradeB:yq2008 Q2` -2.276e-02  1.363e-03 -16.699  &lt; 2e-16 ***
## `gradeC:yq2008 Q2` -3.376e-02  1.393e-03 -24.238  &lt; 2e-16 ***
## `gradeD:yq2008 Q2` -4.730e-02  1.647e-03 -28.722  &lt; 2e-16 ***
## `gradeE:yq2008 Q2` -5.147e-02  2.910e-03 -17.689  &lt; 2e-16 ***
## `gradeF:yq2008 Q2` -5.828e-02  3.592e-03 -16.222  &lt; 2e-16 ***
## `gradeG:yq2008 Q2`         NA         NA      NA       NA    
## `gradeB:yq2008 Q3` -2.025e-02  1.740e-03 -11.643  &lt; 2e-16 ***
## `gradeC:yq2008 Q3` -3.116e-02  1.668e-03 -18.675  &lt; 2e-16 ***
## `gradeD:yq2008 Q3` -4.498e-02  2.101e-03 -21.410  &lt; 2e-16 ***
## `gradeE:yq2008 Q3` -4.674e-02  3.008e-03 -15.539  &lt; 2e-16 ***
## `gradeF:yq2008 Q3` -5.667e-02  4.071e-03 -13.918  &lt; 2e-16 ***
## `gradeG:yq2008 Q3`         NA         NA      NA       NA    
## `gradeB:yq2008 Q4` -1.846e-02  1.018e-03 -18.131  &lt; 2e-16 ***
## `gradeC:yq2008 Q4` -3.049e-02  1.053e-03 -28.960  &lt; 2e-16 ***
## `gradeD:yq2008 Q4` -4.384e-02  1.289e-03 -34.018  &lt; 2e-16 ***
## `gradeE:yq2008 Q4` -4.912e-02  1.676e-03 -29.304  &lt; 2e-16 ***
## `gradeF:yq2008 Q4` -5.311e-02  3.907e-03 -13.591  &lt; 2e-16 ***
## `gradeG:yq2008 Q4` -5.530e-02  5.536e-03  -9.990  &lt; 2e-16 ***
## `gradeB:yq2009 Q1` -1.309e-02  9.321e-04 -14.042  &lt; 2e-16 ***
## `gradeC:yq2009 Q1` -2.475e-02  8.185e-04 -30.243  &lt; 2e-16 ***
## `gradeD:yq2009 Q1` -4.047e-02  9.186e-04 -44.058  &lt; 2e-16 ***
## `gradeE:yq2009 Q1` -4.418e-02  1.249e-03 -35.360  &lt; 2e-16 ***
## `gradeF:yq2009 Q1` -4.824e-02  2.811e-03 -17.163  &lt; 2e-16 ***
## `gradeG:yq2009 Q1`         NA         NA      NA       NA    
## `gradeB:yq2009 Q2` -1.349e-02  7.243e-04 -18.629  &lt; 2e-16 ***
## `gradeC:yq2009 Q2` -2.423e-02  7.532e-04 -32.163  &lt; 2e-16 ***
## `gradeD:yq2009 Q2` -4.046e-02  9.254e-04 -43.719  &lt; 2e-16 ***
## `gradeE:yq2009 Q2` -4.477e-02  1.311e-03 -34.143  &lt; 2e-16 ***
## `gradeF:yq2009 Q2` -5.317e-02  2.409e-03 -22.070  &lt; 2e-16 ***
## `gradeG:yq2009 Q2` -5.703e-02  4.104e-03 -13.898  &lt; 2e-16 ***
## `gradeB:yq2009 Q3` -1.142e-02  6.336e-04 -18.025  &lt; 2e-16 ***
## `gradeC:yq2009 Q3` -2.040e-02  6.928e-04 -29.442  &lt; 2e-16 ***
## `gradeD:yq2009 Q3` -3.290e-02  8.752e-04 -37.597  &lt; 2e-16 ***
## `gradeE:yq2009 Q3` -3.720e-02  1.131e-03 -32.880  &lt; 2e-16 ***
## `gradeF:yq2009 Q3` -4.274e-02  1.862e-03 -22.955  &lt; 2e-16 ***
## `gradeG:yq2009 Q3` -4.755e-02  3.162e-03 -15.037  &lt; 2e-16 ***
## `gradeB:yq2009 Q4` -8.484e-03  5.660e-04 -14.991  &lt; 2e-16 ***
## `gradeC:yq2009 Q4` -1.673e-02  6.161e-04 -27.162  &lt; 2e-16 ***
## `gradeD:yq2009 Q4` -2.821e-02  7.049e-04 -40.026  &lt; 2e-16 ***
## `gradeE:yq2009 Q4` -3.367e-02  1.108e-03 -30.399  &lt; 2e-16 ***
## `gradeF:yq2009 Q4` -3.638e-02  1.717e-03 -21.182  &lt; 2e-16 ***
## `gradeG:yq2009 Q4` -3.769e-02  2.556e-03 -14.743  &lt; 2e-16 ***
## `gradeB:yq2010 Q1` -1.069e-02  5.403e-04 -19.793  &lt; 2e-16 ***
## `gradeC:yq2010 Q1` -1.152e-02  6.007e-04 -19.181  &lt; 2e-16 ***
## `gradeD:yq2010 Q1` -2.162e-02  6.842e-04 -31.604  &lt; 2e-16 ***
## `gradeE:yq2010 Q1` -2.495e-02  1.015e-03 -24.572  &lt; 2e-16 ***
## `gradeF:yq2010 Q1` -3.069e-02  1.794e-03 -17.109  &lt; 2e-16 ***
## `gradeG:yq2010 Q1` -2.975e-02  3.106e-03  -9.579  &lt; 2e-16 ***
## `gradeB:yq2010 Q2` -9.918e-03  4.801e-04 -20.658  &lt; 2e-16 ***
## `gradeC:yq2010 Q2` -8.566e-03  5.269e-04 -16.259  &lt; 2e-16 ***
## `gradeD:yq2010 Q2` -1.868e-02  5.939e-04 -31.450  &lt; 2e-16 ***
## `gradeE:yq2010 Q2` -2.297e-02  7.790e-04 -29.481  &lt; 2e-16 ***
## `gradeF:yq2010 Q2` -2.840e-02  1.314e-03 -21.615  &lt; 2e-16 ***
## `gradeG:yq2010 Q2` -2.822e-02  2.662e-03 -10.603  &lt; 2e-16 ***
## `gradeB:yq2010 Q3` -7.449e-03  4.609e-04 -16.161  &lt; 2e-16 ***
## `gradeC:yq2010 Q3` -5.011e-03  5.056e-04  -9.912  &lt; 2e-16 ***
## `gradeD:yq2010 Q3` -1.704e-02  5.669e-04 -30.065  &lt; 2e-16 ***
## `gradeE:yq2010 Q3` -2.372e-02  6.796e-04 -34.900  &lt; 2e-16 ***
## `gradeF:yq2010 Q3` -2.737e-02  1.094e-03 -25.011  &lt; 2e-16 ***
## `gradeG:yq2010 Q3` -2.538e-02  1.880e-03 -13.497  &lt; 2e-16 ***
## `gradeB:yq2010 Q4` -7.633e-03  4.269e-04 -17.883  &lt; 2e-16 ***
## `gradeC:yq2010 Q4` -9.646e-04  4.811e-04  -2.005 0.044950 *  
## `gradeD:yq2010 Q4` -1.264e-02  5.558e-04 -22.751  &lt; 2e-16 ***
## `gradeE:yq2010 Q4` -1.654e-02  6.724e-04 -24.595  &lt; 2e-16 ***
## `gradeF:yq2010 Q4` -1.944e-02  1.055e-03 -18.426  &lt; 2e-16 ***
## `gradeG:yq2010 Q4` -1.931e-02  1.690e-03 -11.423  &lt; 2e-16 ***
## `gradeB:yq2011 Q1` -5.832e-03  4.113e-04 -14.182  &lt; 2e-16 ***
## `gradeC:yq2011 Q1` -2.389e-03  4.731e-04  -5.050 4.44e-07 ***
## `gradeD:yq2011 Q1` -1.071e-02  5.270e-04 -20.323  &lt; 2e-16 ***
## `gradeE:yq2011 Q1` -1.574e-02  6.063e-04 -25.963  &lt; 2e-16 ***
## `gradeF:yq2011 Q1` -1.816e-02  8.536e-04 -21.279  &lt; 2e-16 ***
## `gradeG:yq2011 Q1` -2.124e-02  1.555e-03 -13.657  &lt; 2e-16 ***
## `gradeB:yq2011 Q2` -1.325e-03  3.914e-04  -3.385 0.000714 ***
## `gradeC:yq2011 Q2`  3.939e-04  4.420e-04   0.891 0.372906    
## `gradeD:yq2011 Q2` -4.201e-03  4.944e-04  -8.497  &lt; 2e-16 ***
## `gradeE:yq2011 Q2` -5.544e-03  5.849e-04  -9.479  &lt; 2e-16 ***
## `gradeF:yq2011 Q2` -5.154e-03  8.427e-04  -6.117 9.65e-10 ***
## `gradeG:yq2011 Q2` -1.097e-02  1.592e-03  -6.891 5.64e-12 ***
## `gradeB:yq2011 Q3`  1.314e-03  3.653e-04   3.597 0.000322 ***
## `gradeC:yq2011 Q3`  2.389e-03  4.221e-04   5.658 1.54e-08 ***
## `gradeD:yq2011 Q3` -3.512e-04  4.749e-04  -0.739 0.459614    
## `gradeE:yq2011 Q3`  1.606e-03  5.763e-04   2.787 0.005323 ** 
## `gradeF:yq2011 Q3`  9.302e-04  8.587e-04   1.083 0.278713    
## `gradeG:yq2011 Q3` -1.694e-03  1.643e-03  -1.032 0.302311    
## `gradeB:yq2011 Q4`         NA         NA      NA       NA    
## `gradeC:yq2011 Q4`         NA         NA      NA       NA    
## `gradeD:yq2011 Q4`         NA         NA      NA       NA    
## `gradeE:yq2011 Q4`         NA         NA      NA       NA    
## `gradeF:yq2011 Q4`         NA         NA      NA       NA    
## `gradeG:yq2011 Q4`         NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.007564 on 37738 degrees of freedom
## Multiple R-squared:  0.9589, Adjusted R-squared:  0.9588 
## F-statistic:  6780 on 130 and 37738 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>data.frame(
  time1$results$RMSE,
  time2$results$RMSE,
  time3$results$RMSE,
  time4$results$RMSE)</code></pre>
<p><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:time trends">
<col><col><col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">time1.results.RMSE</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">time2.results.RMSE</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">time3.results.RMSE</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">time4.results.RMSE</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.0103</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.00905</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.00908</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.00758</td></tr>
</table>

## Q8 Based on your analysis above, is there any evidence to suggest that interest rates change over time? Does including time trends /quarter dummies imrpove predictions? {-}</p>
<blockquote>
<p>Based on our model, there is the evidence to suggest that interest rate change over time is significant. Including time trends or quarter dummier does improve the predictions.</p>
</blockquote>
</div>
<div id="using-bond-yields" class="section level1">
<h1>Using Bond Yields</h1>
<p>One concern with using time trends for forecasting is that in order to make predictions for future loans we will need to project trends to the future. This is an extrapolation that may not be reasonable, especially if macroeconomic conditions in the future change. Furthermore, if we are using quarter dummies, it is not even possible to estimate the coefficient of these dummy variables for future quarters.</p>
<p>Instead, perhaps it’s better to find the reasons as to why different periods are different from one another. The csv file “MonthBondYields.csv” contains information on the yield of US Treasuries on the first day of each month. Can you use it to see if you can improve your predictions without using time dummies?</p>
<pre class="r"><code>#load the data to memory as a dataframe
bond_prices&lt;-readr::read_csv(&quot;/Users/dl/Documents/MAM/individual_portfolio/data/MonthBondYields.csv&quot;)</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X7&#39; [7], &#39;X8&#39; [8], &#39;X9&#39; [9],
## &#39;X10&#39; [10]</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Date = col_character(),
##   Price = col_double(),
##   Open = col_double(),
##   High = col_double(),
##   Low = col_double(),
##   `Change %` = col_character(),
##   X7 = col_logical(),
##   X8 = col_logical(),
##   X9 = col_logical(),
##   X10 = col_logical()
## )</code></pre>
<pre class="r"><code>#make the date of the bond file comparable to the lending club dataset
#for some regional date/number (locale) settings this may not work. If it does try running the following line of code in the Console
#Sys.setlocale(&quot;LC_TIME&quot;,&quot;English&quot;)
bond_prices &lt;- bond_prices %&gt;%
  mutate(Date2=as.Date(paste(&quot;01&quot;,Date,sep=&quot;-&quot;),&quot;%d-%b-%y&quot;)) %&gt;%
  select(-starts_with(&quot;X&quot;))

#let&#39;s see what happened to bond yields over time. Lower bond yields mean the cost of borrowing has gone down.

bond_prices %&gt;%
  ggplot(aes(x=Date2, y=Price))+geom_point(size=0.1, alpha=0.5)</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/bond%20yields-1.png" width="672" /></p>
<pre class="r"><code>#join the data using a left join
lc_with_bonds&lt;-lc_clean %&gt;%
  left_join(bond_prices, by = c(&quot;issue_d&quot; = &quot;Date2&quot;)) %&gt;%
  arrange(issue_d) %&gt;%
  filter(!is.na(Price)) #drop any observations where there re no bond prices available

# investigate graphically if there is a relationship 
lc_with_bonds%&gt;%
  ggplot(aes(x=int_rate, y=Price))+geom_point(size=0.1, alpha=0.5)+geom_smooth(method=&quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/bond%20yields-2.png" width="672" /></p>
<pre class="r"><code>lc_with_bonds%&gt;%
  ggplot(aes(x=int_rate, y=Price, color=grade))+geom_point(size=0.1, alpha=0.5)+geom_smooth(method=&quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/Lending_Club_Workshop_3_files/figure-html/bond%20yields-3.png" width="672" /></p>
<pre class="r"><code>#let&#39;s train a model using the bond information


plsFit&lt;-train(
    int_rate ~loan_amnt*grade+ term+ dti + Price*grade , #fill your variables here 
    lc_with_bonds,
   method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE 
## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(plsFit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.117450 -0.005810 -0.000302  0.006494  0.040734 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         6.791e-02  5.361e-04 126.679  &lt; 2e-16 ***
## loan_amnt           1.795e-07  1.863e-08   9.638  &lt; 2e-16 ***
## gradeB              5.350e-02  6.990e-04  76.538  &lt; 2e-16 ***
## gradeC              8.631e-02  7.843e-04 110.051  &lt; 2e-16 ***
## gradeD              1.192e-01  8.941e-04 133.269  &lt; 2e-16 ***
## gradeE              1.433e-01  1.167e-03 122.786  &lt; 2e-16 ***
## gradeF              1.667e-01  1.791e-03  93.096  &lt; 2e-16 ***
## gradeG              1.903e-01  3.456e-03  55.057  &lt; 2e-16 ***
## term60              1.506e-03  1.323e-04  11.378  &lt; 2e-16 ***
## dti                 2.802e-05  7.453e-06   3.760 0.000171 ***
## Price               1.301e-03  1.626e-04   8.005 1.22e-15 ***
## `loan_amnt:gradeB` -9.477e-08  2.249e-08  -4.214 2.51e-05 ***
## `loan_amnt:gradeC` -2.195e-07  2.416e-08  -9.088  &lt; 2e-16 ***
## `loan_amnt:gradeD` -1.987e-09  2.572e-08  -0.077 0.938417    
## `loan_amnt:gradeE`  6.441e-08  2.787e-08   2.311 0.020827 *  
## `loan_amnt:gradeF`  6.990e-08  3.840e-08   1.820 0.068693 .  
## `loan_amnt:gradeG` -1.206e-07  6.770e-08  -1.781 0.074911 .  
## `gradeB:Price`     -5.774e-03  2.181e-04 -26.470  &lt; 2e-16 ***
## `gradeC:Price`     -8.000e-03  2.429e-04 -32.934  &lt; 2e-16 ***
## `gradeD:Price`     -1.274e-02  2.794e-04 -45.585  &lt; 2e-16 ***
## `gradeE:Price`     -1.527e-02  3.611e-04 -42.287  &lt; 2e-16 ***
## `gradeF:Price`     -1.667e-02  5.359e-04 -31.103  &lt; 2e-16 ***
## `gradeG:Price`     -1.780e-02  9.982e-04 -17.829  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.009584 on 37845 degrees of freedom
## Multiple R-squared:  0.9339, Adjusted R-squared:  0.9339 
## F-statistic: 2.43e+04 on 22 and 37845 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="q9.-do-bond-yields-have-any-explanatory-power" class="section level2">
<h2>Q9. Do bond yields have any explanatory power?</h2>
<blockquote>
<p>Answer here: From the above, after including in our model “Price”, we can infer that the bonds have the explanatory power. However, the explanatory power increases our Adjusted R-squared less than the time trend/quarter variables.</p>
</blockquote>
</div>
<div id="q10.-choose-a-model-and-describe-your-methodology" class="section level2 unnumbered">
<h2>Q10. Choose a model and describe your methodology</h2>
<p>Feel free to investigate more models with different features using the methodologies covered so far. Present the model you believe predicts interest rates the best. Describe how good it is (including the approximate length of the 95% Confidence Interval of predictions that use this model) and what features it uses. What methodology did you use to choose it? (Do not use time trends or quarter dummies in your model as the first cannot be extrapolated into the future reliably and the second cannot be even estimated for future quarters.)</p>
<blockquote>
<p>We were trying to add even more variables to our model, however, many of them turned out not to be significant. Our final model can be observed below. It has an explanatory power with adjusted R-squared of 93.57%. Tt has a Confidence Interval at 95% of ±0.01852592%. It can be used to accuratley predict the mean. We used the linear model with method of stepwise k-fold cross validation.</p>
</blockquote>
<pre class="r"><code>lc_with_yq_bonds&lt;- lc_with_bonds %&gt;% 
  mutate(yq = as.factor(as.yearqtr(issue_d, format = &quot;%Y-%m-%d&quot;)))

model_wild_west &lt;- train(
    int_rate ~loan_amnt*grade+ term+ dti + poly(Price, 3)*grade, #fill your variables here 
    lc_with_yq_bonds,
   method = &quot;lm&quot;,
    trControl = control
   )</code></pre>
<pre><code>## + Fold01: intercept=TRUE 
## - Fold01: intercept=TRUE 
## + Fold02: intercept=TRUE 
## - Fold02: intercept=TRUE 
## + Fold03: intercept=TRUE 
## - Fold03: intercept=TRUE 
## + Fold04: intercept=TRUE 
## - Fold04: intercept=TRUE 
## + Fold05: intercept=TRUE 
## - Fold05: intercept=TRUE 
## + Fold06: intercept=TRUE 
## - Fold06: intercept=TRUE 
## + Fold07: intercept=TRUE 
## - Fold07: intercept=TRUE 
## + Fold08: intercept=TRUE 
## - Fold08: intercept=TRUE 
## + Fold09: intercept=TRUE 
## - Fold09: intercept=TRUE 
## + Fold10: intercept=TRUE 
## - Fold10: intercept=TRUE 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>summary(model_wild_west)</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.114899 -0.006111  0.000080  0.006341  0.041524 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               7.170e-02  2.062e-04 347.715  &lt; 2e-16 ***
## loan_amnt                 1.771e-07  1.838e-08   9.638  &lt; 2e-16 ***
## gradeB                    3.692e-02  2.470e-04 149.477  &lt; 2e-16 ***
## gradeC                    6.338e-02  2.713e-04 233.592  &lt; 2e-16 ***
## gradeD                    8.281e-02  3.160e-04 262.055  &lt; 2e-16 ***
## gradeE                    9.977e-02  4.243e-04 235.133  &lt; 2e-16 ***
## gradeF                    1.190e-01  7.096e-04 167.760  &lt; 2e-16 ***
## gradeG                    1.402e-01  1.445e-03  97.073  &lt; 2e-16 ***
## term60                    1.678e-03  1.321e-04  12.702  &lt; 2e-16 ***
## dti                       2.666e-05  7.360e-06   3.622 0.000293 ***
## `poly(Price, 3)1`         1.640e-01  1.904e-02   8.614  &lt; 2e-16 ***
## `poly(Price, 3)2`         3.282e-01  1.890e-02  17.369  &lt; 2e-16 ***
## `poly(Price, 3)3`        -5.334e-02  1.796e-02  -2.970 0.002977 ** 
## `loan_amnt:gradeB`       -1.057e-07  2.221e-08  -4.761 1.93e-06 ***
## `loan_amnt:gradeC`       -2.275e-07  2.385e-08  -9.537  &lt; 2e-16 ***
## `loan_amnt:gradeD`       -2.769e-08  2.545e-08  -1.088 0.276645    
## `loan_amnt:gradeE`        3.504e-08  2.768e-08   1.266 0.205536    
## `loan_amnt:gradeF`        4.849e-08  3.820e-08   1.270 0.204262    
## `loan_amnt:gradeG`       -1.688e-07  6.741e-08  -2.504 0.012273 *  
## `gradeB:poly(Price, 3)1` -6.953e-01  2.555e-02 -27.217  &lt; 2e-16 ***
## `gradeC:poly(Price, 3)1` -9.351e-01  2.853e-02 -32.776  &lt; 2e-16 ***
## `gradeD:poly(Price, 3)1` -1.537e+00  3.275e-02 -46.930  &lt; 2e-16 ***
## `gradeE:poly(Price, 3)1` -1.833e+00  4.297e-02 -42.658  &lt; 2e-16 ***
## `gradeF:poly(Price, 3)1` -1.967e+00  6.324e-02 -31.094  &lt; 2e-16 ***
## `gradeG:poly(Price, 3)1` -2.205e+00  1.334e-01 -16.529  &lt; 2e-16 ***
## `gradeB:poly(Price, 3)2` -1.284e-01  2.581e-02  -4.973 6.62e-07 ***
## `gradeC:poly(Price, 3)2` -4.488e-01  2.740e-02 -16.381  &lt; 2e-16 ***
## `gradeD:poly(Price, 3)2` -2.985e-01  3.263e-02  -9.147  &lt; 2e-16 ***
## `gradeE:poly(Price, 3)2` -2.612e-01  4.497e-02  -5.809 6.35e-09 ***
## `gradeF:poly(Price, 3)2` -3.536e-01  6.094e-02  -5.802 6.61e-09 ***
## `gradeG:poly(Price, 3)2`  5.936e-02  1.739e-01   0.341 0.732898    
## `gradeB:poly(Price, 3)3` -8.692e-02  2.552e-02  -3.406 0.000659 ***
## `gradeC:poly(Price, 3)3` -1.702e-01  2.664e-02  -6.387 1.71e-10 ***
## `gradeD:poly(Price, 3)3` -3.553e-01  3.385e-02 -10.496  &lt; 2e-16 ***
## `gradeE:poly(Price, 3)3` -3.433e-01  4.443e-02  -7.727 1.13e-14 ***
## `gradeF:poly(Price, 3)3` -2.343e-01  5.338e-02  -4.390 1.14e-05 ***
## `gradeG:poly(Price, 3)3` -4.176e-01  1.825e-01  -2.288 0.022128 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.009452 on 37831 degrees of freedom
## Multiple R-squared:  0.9357, Adjusted R-squared:  0.9357 
## F-statistic: 1.53e+04 on 36 and 37831 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="#ZgotmplZ" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com/in/derekleung0306" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; London Business School</li>
                
                <li>Design:  <a href="https://www.html5up.net">HTML5 UP</a></li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
